name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: denoland/setup-deno@v2
    - run: deno fmt --check
    - run: deno check
    - run: deno lint
    - run: make test

  check-pg-ver:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-ver:
          - 18
          - 17
          - 16
          - 15
          - 14
    steps:
    - uses: actions/checkout@v6
    - uses: denoland/setup-deno@v2
    - run: make test
      env:
        POSTGRESQL_VER: ${{ matrix.pg-ver }}

  it-node:
    needs:
      - check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
          - 22
          - 24
          - latest
    steps:
    - uses: actions/checkout@v6
    - uses: denoland/setup-deno@v2
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker run -d --rm -ePOSTGRES_PASSWORD=password -p5432:5432 postgres
    - run: make test-it-node
    - run: docker ps -q|xargs docker stop

  it-bun:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: denoland/setup-deno@v2
    - uses: oven-sh/setup-bun@v2
    - run: docker run -d --rm -ePOSTGRES_PASSWORD=password -p5432:5432 postgres
    - run: make test-it-bun
    - run: docker ps -q|xargs docker stop
